"""make category_id primary key

Revision ID: 608648e8c670
Revises: 7bd7dbd7fb89
Create Date: 2026-09-03 19:28:35.366196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608648e8c670'
down_revision = '7bd7dbd7fb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_categories', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_categories', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
