"""changed event end date to not required

Revision ID: 7bd7dbd7fb89
Revises: a32e59f52d3a
Create Date: 2026-09-03 17:14:29.451805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd7dbd7fb89'
down_revision = 'a32e59f52d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('ends_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('ends_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
